// Admin/src/views/auth/components/LoginForm.vue
<template>
  <form @submit.prevent="login" class="space-y-6">
    <div class="space-y-2">
      <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-200">
        <i class="pi pi-envelope mr-2"></i>
        {{ $t('auth.email') }}
      </label>
      <InputText 
        id="email" 
        v-model="email" 
        type="email"
        :class="{'p-invalid': errors.email}"
        :placeholder="$t('auth.emailPlaceholder')"
        class="w-full !p-3 !rounded-lg !border !border-gray-300 dark:!bg-surface-800 dark:!border-surface-700 dark:!text-white focus:!border-primary focus:!ring-2 focus:!ring-primary-200 !transition-colors"
      />
      <small class="text-red-500 text-xs" v-if="errors.email">{{ errors.email[0] }}</small>
    </div>

    <div class="space-y-2">
      <label for="password" class="block text-sm font-medium text-gray-700 dark:text-gray-200">
        <i class="pi pi-lock mr-2"></i>
        {{ $t('auth.password') }}
      </label>
      <Password
        id="password"
        v-model="password"
        :feedback="false"
        :toggleMask="true"
        :class="{'p-invalid': errors.password}"
        :placeholder="$t('auth.passwordPlaceholder')"
        style="width: 100%; display: block;"
        class="dark:bg-surface-800"
        :inputClass="isDarkTheme ? 'dark:bg-surface-800 dark:text-white dark:border-surface-700' : ''"
        :inputStyle="{ 
          width: '100%', 
          padding: '0.75rem', 
          borderRadius: '0.5rem',
          backgroundColor: isDarkTheme ? 'var(--surface-800)' : 'white',
          color: isDarkTheme ? 'var(--surface-50)' : 'inherit',
          borderColor: isDarkTheme ? 'var(--surface-700)' : 'var(--gray-300)'
        }"
        :panelStyle="{ display: 'none' }"
      />
      <small class="text-red-500 text-xs" v-if="errors.password">{{ errors.password[0] }}</small>
    </div>

    <div class="flex items-center">
      <Checkbox 
        v-model="rememberMe" 
        :binary="true" 
        inputId="remember"
        class="mr-2"
      />
      <label for="remember" class="text-sm text-gray-600 dark:text-gray-300 cursor-pointer">
        {{ $t('auth.rememberMe') }}
      </label>
    </div>

    <Button 
      type="submit" 
      :label="$t('auth.signIn')"
      :loading="loading"
      class="w-full p-3 bg-primary hover:bg-primary-600 text-white font-semibold rounded-lg transition-colors"
    />
  </form>
</template>

<script setup>
import { useI18n } from 'vue-i18n'
import { useAuth, useTheme } from '../composables'

const { t } = useI18n()
const { isDarkTheme } = useTheme()
const { email, password, rememberMe, loading, errors, login } = useAuth()
</script>

// User/src/pages/auth/components/LoginForm.jsx
import { Button } from 'primereact/button'
import FormInput from '../../../components/common/FormInput'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { ROUTES } from '../../../constants/routes'
import { Checkbox } from 'primereact/checkbox'

const LoginForm = ({ formData, loading, touched, updateFormData, handleSubmit }) => {
    const { t } = useTranslation()

    return (
        <form onSubmit={handleSubmit} className="flex flex-col gap-2">
            <FormInput
                type="text"
                name="email"
                label={t('auth.email')}
                value={formData.email}
                onChange={(value) => updateFormData('email', value)}
                required
                disabled={loading}
                icon="pi pi-envelope"
                placeholder={t('auth.emailPlaceholder')}
                touched={touched}
                className="dark:text-white [&_.p-inputtext]:dark:text-white [&_label]:dark:text-white [&_i]:dark:text-white"
            />

            <FormInput
                type="password"
                name="password"
                label={t('auth.password')}
                value={formData.password}
                onChange={(value) => updateFormData('password', value)}
                required
                disabled={loading}
                icon="pi pi-lock"
                placeholder={t('auth.passwordPlaceholder')}
                touched={touched}
                className="dark:text-white [&_.p-inputtext]:dark:text-white [&_label]:dark:text-white [&_i]:dark:text-white"
            />

            <div className="flex items-center mt-2">
                <Checkbox
                    inputId="rememberMe"
                    checked={formData.rememberMe}
                    onChange={(e) => updateFormData('rememberMe', e.checked)}
                    disabled={loading}
                    className="mr-2"
                />
                <label htmlFor="rememberMe" className="text-sm text-gray-700 dark:text-white cursor-pointer">
                    {t('auth.rememberMe')}
                </label>
            </div>

            <div className="flex justify-end items-center mt-2">
                <Link
                    to={ROUTES.FORGOT_PASSWORD}
                    className="text-blue-600 hover:text-blue-700 dark:text-white hover:underline text-sm"
                >
                    {t('auth.forgot_password')}
                </Link>
            </div>

            <Button
                type="submit"
                label={t('common.login')}
                icon="pi pi-sign-in"
                loading={loading}
                severity="primary"
                className="mt-4 py-3 px-4 w-full dark:text-white"
            />

            <div className="text-center mt-6">
                <span className="text-gray-600 dark:text-white">
                    {t('auth.noAccount')}{' '}
                </span>
                <Link
                    to={ROUTES.REGISTER}
                    className="text-blue-600 hover:text-blue-700 dark:text-white hover:underline"
                >
                    {t('auth.registerHere')}
                </Link>
            </div>
        </form>
    )
}

export default LoginForm
