// Admin/src/views/auth/Login.vue
<template>
    <div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 to-primary-100 p-8 relative">
        <!-- Language Selector -->
        <div class="absolute top-4 right-4">
            <Dropdown
                v-model="selectedLanguage"
                :options="languages"
                optionLabel="name"
                @change="changeLanguage"
                class="w-40 rounded-lg"
            />
        </div>

        <div class="w-full max-w-md bg-white rounded-2xl shadow-lg p-10">
            <div class="text-center mb-10">
                <i class="pi pi-user text-5xl text-primary mb-4"></i>
                <h1 class="text-3xl font-semibold text-primary mb-2">{{ $t('auth.welcome') }}</h1>
                <p class="text-gray-600">{{ $t('auth.signInToContinue') }}</p>
            </div>

            <form @submit.prevent="handleSubmit" class="space-y-6">
                <div class="space-y-2">
                    <label for="email" class="block text-sm font-medium text-gray-700">
                        <i class="pi pi-envelope mr-2"></i>
                        {{ $t('auth.email') }}
                    </label>
                    <InputText 
                        id="email" 
                        v-model="email" 
                        type="email"
                        :class="{'p-invalid': errors.email}"
                        :placeholder="$t('auth.emailPlaceholder')"
                        class="w-full !p-3 !rounded-lg !border !border-gray-300 focus:!border-primary focus:!ring-2 focus:!ring-primary-200 !transition-colors"
                    />
                    <small class="text-red-500 text-xs" v-if="errors.email">{{ errors.email[0] }}</small>
                </div>

                <div class="space-y-2">
                    <label for="password" class="block text-sm font-medium text-gray-700">
                        <i class="pi pi-lock mr-2"></i>
                        {{ $t('auth.password') }}
                    </label>
                    <Password
                        id="password"
                        v-model="password"
                        :feedback="false"
                        :toggleMask="true"
                        :class="{'p-invalid': errors.password}"
                        :placeholder="$t('auth.passwordPlaceholder')"
                        style="width: 100%; display: block;"
                        :inputStyle="{ width: '100%', padding: '0.75rem', borderRadius: '0.5rem' }"
                        :panelStyle="{ display: 'none' }"
                    />
                    <small class="text-red-500 text-xs" v-if="errors.password">{{ errors.password[0] }}</small>
                </div>

                <div class="flex items-center">
                    <Checkbox 
                        v-model="rememberMe" 
                        :binary="true" 
                        inputId="remember"
                        class="mr-2"
                    />
                    <label for="remember" class="text-sm text-gray-600 cursor-pointer">
                        {{ $t('auth.rememberMe') }}
                    </label>
                </div>

                <Button 
                    type="submit" 
                    :label="$t('auth.signIn')"
                    :loading="loading"
                    class="w-full p-3 bg-primary hover:bg-primary-600 text-white font-semibold rounded-lg transition-colors"
                />
            </form>
        </div>
    </div>
</template>

<script setup>
import { ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from 'primevue/usetoast'
import { useRouter } from 'vue-router'
import AuthService from './services/auth'

const { t, locale } = useI18n()
const toast = useToast()
const router = useRouter()

const email = ref('')
const password = ref('')
const rememberMe = ref(false)
const loading = ref(false)
const errors = ref({})

const languages = [
    { name: 'English', code: 'en' },
    { name: 'Tiếng Việt', code: 'vi' },
    { name: '한국어', code: 'ko' }
]

// Khởi tạo ngôn ngữ từ localStorage hoặc mặc định
const savedLanguage = localStorage.getItem('language')
const defaultLanguage = languages.find(lang => lang.code === savedLanguage) || languages[0]
const selectedLanguage = ref(defaultLanguage)

// Cập nhật locale khi component được tạo
locale.value = selectedLanguage.value.code

const changeLanguage = (event) => {
    const newLang = event.value.code
    localStorage.setItem('language', newLang)
    locale.value = newLang // Cập nhật locale ngay lập tức
}

// Watch để theo dõi thay đổi của locale
watch(locale, (newLocale) => {
    console.log('Language changed to:', newLocale)
})

const handleSubmit = async () => {
    try {
        loading.value = true
        errors.value = {}
        
        const response = await AuthService.login({
            email: email.value,
            password: password.value,
            remember_me: rememberMe.value
        })

        localStorage.setItem('admin_token', response.token)
        localStorage.setItem('admin_user', response.user)

        if (response.status === 200) {
            toast.add({
                severity: 'success',
                summary: t('auth.success'),
                detail: t('auth.loginSuccess'),
                life: 3000
            })
            router.push('/')
        }
    } catch (error) {
        console.log('Login error:', JSON.stringify(error.status, null, 2))
        if (error.response?.status === 422) {
            errors.value = error.response.data.errors
        } 
        else if(error.status === 401) {
            toast.add({
                severity: 'error',
                summary: t('auth.error'),
                detail: t('auth.loginError'),
                life: 3000
            })
        }
    } finally {
        loading.value = false
    }
}
</script>

// User/src/pages/auth/Login.jsx
import { useState, useEffect } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Card } from 'primereact/card'
import { Button } from 'primereact/button'
import { Toast } from 'primereact/toast'
import { useRef } from 'react'
import authService from '../../services/auth.service'
import { ROUTES } from '../../constants/routes'
import FormInput from '../../components/common/FormInput'
import { useTranslation } from 'react-i18next'
import ThemeSwitcher from '../../components/common/ThemeSwitcher'
import LanguageSwitcher from '../../components/common/LanguageSwitcher'

const Login = () => {
    const navigate = useNavigate()
    const toast = useRef(null)
    const { t } = useTranslation()
    const [loading, setLoading] = useState(false)
    const [touched, setTouched] = useState(false)
    const [loginError, setLoginError] = useState(null)
    const [formData, setFormData] = useState({
        email: '',
        password: ''
    })

    const [isSubmit, setIsSubmit] = useState(false);

    console.log("loginError: ", loginError)

    const handleSubmit = async (e) => {
        e.preventDefault()
        setTouched(true)
        // setLoginError(null)
        
        // Validate form
        let hasError = false;
        if (!formData.email) {
            toast.current.show({
                severity: 'error',
                summary: t('common.error'),
                detail: t('auth.emailRequired'),
                life: 6000,
            });
            hasError = true;
        } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(formData.email)) {
            toast.current.show({
                severity: 'error',
                summary: t('common.error'),
                detail: t('auth.emailInvalid'),
                life: 6000,
            });
            hasError = true;
        }

        if (!formData.password) {
            toast.current.show({
                severity: 'error',
                summary: t('common.error'),
                detail: t('auth.passwordRequired'),
                life: 6000,
            });
            hasError = true;
        } else if (formData.password.length < 6) {
            toast.current.show({
                severity: 'error',
                summary: t('common.error'),
                detail: t('auth.passwordMinLength'),
                life: 6000,
            });
            hasError = true;
        }

        if (hasError) {
            return;
        }
        
        setLoading(true)
        try {
            const response = await authService.login(formData)
            window.dispatchEvent(new Event('auth-change'))
            
            toast.current.show({
                severity: 'success',
                summary: t('common.success'),
                detail: response?.message || t('auth.loginSuccess'),
                life: 6000,
            })

            setTimeout(() => {
                navigate(ROUTES.HOME)
            }, 2000)

        } catch (error) {
            console.error("Login error:", error)
            
            // Đảm bảo luôn có message để hiển thị
            let errorMessage;
            if (error?.response?.data?.message) {
                errorMessage = error.response.data.message;
            } else if (error?.message) {
                errorMessage = error.message;
            } else {
                errorMessage = t('auth.invalidCredentials');
            }
            
            setLoginError(errorMessage);
            
            // Hiển thị toast lỗi
            if (toast.current) {
                toast.current.show({
                    severity: 'error',
                    summary: t('common.error'),
                    detail: errorMessage,
                    life: 6000,
                    sticky: true
                });
            }
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="flex justify-center items-center min-h-screen bg-gray-50 dark:bg-gray-900">
            <Toast ref={toast} baseZIndex={1000} position="top-right" />
            
            <div className="fixed top-4 right-4 flex items-center gap-2">
                <ThemeSwitcher />
                <LanguageSwitcher />
            </div>

            <Card className="w-full max-w-md shadow-lg border-0 bg-white dark:bg-gray-800 dark:text-white">
                <div className="text-center mb-6">
                    <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                        {t('common.login')}
                    </h1>
                    <p className="text-gray-600 dark:text-white">
                        {t('common.loginWelcome')}
                    </p>
                </div>

                <form onSubmit={handleSubmit} className="flex flex-col gap-2">
                    <FormInput
                        type="text"
                        name="email"
                        label={t('auth.email')}
                        value={formData.email}
                        onChange={(value) => setFormData(prev => ({ ...prev, email: value }))}
                        required
                        disabled={loading}
                        icon="pi pi-envelope"
                        placeholder={t('auth.emailPlaceholder')}
                        touched={touched}
                        className="dark:text-white [&_.p-inputtext]:dark:text-white [&_label]:dark:text-white [&_i]:dark:text-white"
                    />

                    <FormInput
                        type="password"
                        name="password"
                        label={t('auth.password')}
                        value={formData.password}
                        onChange={(value) => setFormData(prev => ({ ...prev, password: value }))}
                        required
                        disabled={loading}
                        icon="pi pi-lock"
                        placeholder={t('auth.passwordPlaceholder')}
                        touched={touched}
                        className="dark:text-white [&_.p-inputtext]:dark:text-white [&_label]:dark:text-white [&_i]:dark:text-white"
                    />

                    <Button 
                        type="submit" 
                        label={t('common.login')}
                        icon="pi pi-sign-in"
                        loading={loading}
                        severity="primary"
                        className="mt-4 py-3 px-4 w-full dark:text-white"
                    />

                    <div className="text-center mt-6">
                        <span className="text-gray-600 dark:text-white">
                            {t('auth.noAccount')}{' '}
                        </span>
                        <Link 
                            to={ROUTES.REGISTER} 
                            className="text-blue-600 hover:text-blue-700 dark:text-white hover:underline"
                        >
                            {t('auth.registerHere')}
                        </Link>
                    </div>
                </form>
            </Card>
        </div>
    )
}

export default Login
